version: "3"
services:
  react-app:
    image: react-app:latest
#    build:
#      context: ./react-app
#      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - nodejs-app
  nodejs-app:
    image: nodejs-app:latest
#    build:
#      context: nodejs-app
#      dockerfile: Dockerfile
    ports:
      - "3001:3001"
